### ISSUE TITLE
Multi GPU mining 

### ISSUE THREAD

**Issue by murph7andrew** [azlehria/0xbitcoin-gpuminer#2]
I have an 8 GPU rig, how would I go about having cuda use more than just default device 0?

**Comment by minerjoe77** [comment]
You can assign it per device here's a quick vid for reference

https://youtu.be/ALh6DaRPob8

**Comment by xklob** [comment]
How do you do this on the Linux build?

**Comment by azlehria** [comment]
This is now fixed in the most recent releases, so I'm going to close it.
